### ISSUE TITLE
coc-ci Request timeout after 10000ms

### ISSUE THREAD

**Issue by JamesWZM** [fannheyward/coc-ci#75]
coc-ci Request timeout after 10000ms

如何手动安装？无论是vim-plug还是cocinstall最近都timeout，非常难受

**Comment by fannheyward** [comment]
手动安装：

1. `git clone https://github.com/fannheyward/coc-ci.git` 或者下载代码到你本地
2. cd 到目录，`yarn install` 即可
3. 在你的 vimrc 设置 `set runtimepath^=/path/to/coc-ci`
